export const smallGameList = [
    "Catan", "Carcassonne", "Splendor"
]

export const gameList = [
    "13 Beco da Traição",
    "2491 Planetship",
    "7 Wonders",
    "7 Wonders Duel",
    "A Ilha proibida",
    "A cabana abandonada",
    "A nossa casa",
    "Abalone",
    "Akropolis",
    "Alien - starter set",
    "Aqualin",
    "Arraial",
    "Aventuras Fantasticas",
    "Baby blues",
    "Battle Cry",
    "Blue Lion",
    "Boomerang",
    "Boss monster",
    "Bot factory",
    "Cactus",
    "Call to adventure",
    "Camel Up",
    "Captain Flip",
    "Caravelas",
    "Carcassonne",
    "Cards Lab",
    "Caretos",
    "Carrossel",
    "Cartographers",
    "Castelo S. Jorge",
    "Castle Party",
    "Cat Lady",
    "Catan",
    "Celtae",
    "Civilization",
    "Clube detective",
    "Cluedo",
    "Codigo secreto - Imagens",
    "Combo Cone Paradise",
    "Coup",
    "D. Afonso Henriques",
    "Deception - Murder in Hong kong",
    "Diplomacy",
    "Dirty Money",
    "Disciple Detective",
    "Dixit",
    "Douro",
    "Down force - Corrida de alto risco",
    "Draft and write - Records",
    "Dragon Scales",
    "Drunter  Druber",
    "Eight minute empire",
    "Ekipas Eclipse",
    "El puerto fluvial",
    "Era uma vez",
    "Escape room - Prison Island",
    "Estoril 1942",
    "Evergreen",
    "Evo",
    "Evolution",
    "Evora",
    "Faraway",
    "Fiesta de los muertos",
    "Floresta Misteriosa",
    "FlussFieber",
    "F1",
    "Formula D",
    "Gardens",
    "Garum",
    "Gods of Rome",
    "HExplore it",
    "Hedbanz",
    "History of the World",
    "Hook!",
    "I Love Portugal",
    "Illusion",
    "Istanbul",
    "Japanese Islands",
    "Kamisado",
    "Kingdomino",
    "Klash",
    "Kokopelli",
    "La cucaracha",
    "Lata",
    "Letraletra",
    "Lost Cities",
    "Love Letter",
    "Lunaris 45",
    "Magellan Elcano",
    "MicroMacro: Crime City",
    "Mille Fiori ",
    "Mindtrap II",
    "Missao M",
    "Mistakos",
    "Modern Art",
    "Monopoly",
    "Monster Lands",
    "Mosteiro",
    "Mysthea",
    "New york 1901",
    "Nidavellir",
    "Nuts!",
    "O Misterio do marques do pombal",
    "O Palacio do Marques",
    "O Rei de Tóquio",
    "OK Boomer",
    "On Tour",
    "One key",
    "OverBoss",
    "Papua",
    "Passa o Desenho",
    "Pega Bicho",
    "Pessoa",
    "Pick a Pig",
    "Planet Unknown ",
    "Porto",
    "Potions Explosions",
    "Quacksalber",
    "Quicksand",
    "Quinto Imperio",
    "Quoridor",
    "Ragami",
    "Ratoeira",
    "Red 7",
    "Reis de Portugal",
    "Rey de 12",
    "Rhino Hero",
    "Rossio",
    "Saboteur",
    "Sagrada",
    "Salem 1692",
    "Salto",
    "Scattergories",
    "Scotland Yard",
    "Selva",
    "Sequence",
    "Shark Park",
    "Shepherd Mess",
    "So Clover!",
    "Space Base",
    "Spaghetti",
    "Splendor",
    "Star Wars X-wing",
    "Team 3",
    "Terra",
    "Terra Mare",
    "Terraforming Mars",
    "That's a question",
    "That's not a Hat",
    "The Builders Antiquity",
    "The Resistance",
    "The Vale of Eternity",
    "Three Sisters",
    "Timeline",
    "Top ten",
    "Trails of Tucana",
    "Trumple!",
    "Unearth",
    "Vidrado",
    "Village",
    "Vintage",
    "Viral",
    "War! Age of Imperialism",
    "Wavelength",
    "Why First?",
    "Wildlife",
    "Wisdom of Solomon",
    "Ticket to ride",

]